name: Main

on:
  pull_request:
    branches:
      - 10.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      # todo - we need to update the settings.xml file to use maven-internal

      - name: Build nuxeo-web-ui-itests package
        run: mvn clean install
